language: go

go:
- 1.12.x

git:
  depth: 1

env:
  global:
    - GO111MODULE=on
    - KUBEBUILDER_CONTROLPLANE_START_TIMEOUT=600s

install: skip

jobs:
  include:

    - stage: unit-test
      script:
      - which kubebuilder && which kubectl && which ls
      - ls /usr/local/kubebuilder
      - ls $HOME/ && ls $HOME/opt && ls $HOME/opt/kubebuilder
      - go test -v ./api/... ./controllers/... ./metrics/... ./store/... -coverprofile coverage.txt
      - bash <(curl -s https://codecov.io/bash)

    - stage: publish-image
      if: type = push
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - export IMG=orkaproj/active-monitor:$TRAVIS_BRANCH
      - make docker-build
      - make docker-push