language: go

go:
- 1.12.x

git:
  depth: 1

env:
  global:
    - GO111MODULE=on

install: skip

jobs:
  include:

    - stage: unit-test
      script:
      - wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.0.0-beta.0/kubebuilder_2.0.0-beta.0_linux_amd64.tar.gz
      - tar -zxvf  kubebuilder_2.0.0-beta.0_linux_amd64.tar.gz
      - mv kubebuilder_2.0.0-beta.0_linux_amd64 /usr/local/kubebuilder
      - go test -v ./api/... ./controllers/... ./metrics/... ./store/... -coverprofile coverage.txt
      - bash <(curl -s https://codecov.io/bash)

    - stage: publish-image
      if: type = push
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - export IMG=orkaproj/active-monitor:$TRAVIS_BRANCH
      - make docker-build
      - make docker-push