language: go

go:
- 1.12.x

git:
  depth: 1

env:
  global:
  - GO111MODULE=on
  - KUBECONFIG=$HOME/.kube/config

cache:
  directories:
  - $HOME/.local
  - $HOME/.kube

before_install:
- pip install --user awscli
- curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl $HOME/.local/bin
- curl -sSL -o $HOME/.local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x $HOME/.local/bin/jq
- export PATH=$PATH:$HOME/.local/bin
- jq --version
- kubectl
- aws --version

install:
  # install dependencies needed by jobs
  - wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.2.0/kubebuilder_2.2.0_linux_amd64.tar.gz
  - tar -zxvf  kubebuilder_2.2.0_linux_amd64.tar.gz
  - sudo mv kubebuilder_2.2.0_linux_amd64 /usr/local/kubebuilder

jobs:
  include:
    - stage: unit-test
      script:
      - make test
      - bash <(curl -s https://codecov.io/bash)

    - stage: publish-image
      if: type = push
      script:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - if [ $TRAVIS_TAG != "" ]; then export IMG=keikoproj/active-monitor:$($TRAVIS_TAG | cut -c1-7); else export IMG=keikoproj/active-monitor:$TRAVIS_COMMIT; fi
      - make docker-build
      - make docker-push